/** @type {import('tailwindcss').Config} */
// Warna/tipografi/spacing diambil dari referensi desain Stitch (stitch/DESIGN.md,
// stitch/sesi_review_ripen/code.html, stitch/dashboard_ripen/code.html) — jangan
// ubah nilai token di sini tanpa menyamakan lagi ke referensi Stitch yang sudah
// direview.
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "surface-dim": "#dbdad5",
        "on-primary-container": "#99baa1",
        "surface-container": "#f0eee9",
        "surface-variant": "#e4e2dd",
        "hard-orange": "#E5A462",
        outline: "#727972",
        "wood-warm": "#5C5346",
        "on-background": "#1b1c19",
        "secondary-fixed": "#ccebc8",
        "unripe-pale": "#DEE5D4",
        "primary-fixed": "#c8ebd0",
        "again-red": "#D16A5E",
        "on-tertiary-fixed": "#1f1b13",
        primary: "#163422",
        "secondary-container": "#ccebc8",
        surface: "#fbf9f4",
        secondary: "#4a654a",
        "surface-bright": "#fbf9f4",
        "on-primary-fixed-variant": "#2f4d39",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#2d4b37",
        "on-tertiary-container": "#bab1a5",
        "surface-container-highest": "#e4e2dd",
        background: "#fbf9f4",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#022110",
        tertiary: "#332e25",
        "surface-container-high": "#eae8e3",
        "on-secondary-fixed": "#07200b",
        "easy-blue": "#6B8E9E",
        "primary-fixed-dim": "#adcfb4",
        "ripe-forest": "#1B3022",
        "tertiary-container": "#4a443b",
        "tertiary-fixed-dim": "#cfc5b9",
        "on-secondary-container": "#506b50",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#b0ceae",
        "good-green": "#8BA889",
        "inverse-on-surface": "#f2f1ec",
        "surface-container-low": "#f5f3ee",
        "on-tertiary-fixed-variant": "#4c463c",
        "tertiary-fixed": "#ebe1d4",
        "on-surface": "#1b1c19",
        "on-error-container": "#93000a",
        "outline-variant": "#c2c8c0",
        "surface-tint": "#466550",
        "inverse-surface": "#30312e",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#334d34",
        "inverse-primary": "#adcfb4",
        error: "#ba1a1a",
        "on-surface-variant": "#424843",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        md: "16px",
        xs: "4px",
        unit: "4px",
        "reading-width": "680px",
        "container-max": "1120px",
        sm: "8px",
        xl: "48px",
        lg: "24px",
      },
      fontFamily: {
        "pinyin-ruby": ["var(--font-be-vietnam-pro)"],
        "body-md": ["var(--font-be-vietnam-pro)"],
        "label-caps": ["var(--font-jetbrains-mono)"],
        "headline-md": ["var(--font-manrope)"],
        "body-lg": ["var(--font-be-vietnam-pro)"],
        "display-lg": ["var(--font-manrope)"],
        "headline-hanzi": ["var(--font-manrope)"],
      },
      fontSize: {
        "pinyin-ruby": ["12px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "30px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-hanzi": ["64px", { lineHeight: "80px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
